"""Photos: from a phone frame to three WebP files and a URL.

Everything that touches a picture happens here — reading the upload, deciding
whether it is really an image, turning it, resizing it and putting it on the
volume. The routers stay on schemas and sessions (§13.3), so swapping the
volume for something else is a change to this file alone.

Three rules the rest of the project relies on:

  * the format is decided by **magic bytes**, never by the extension or the
    MIME the browser volunteered — Safari hands over a HEIC frame with an empty
    type, and anyone can rename a PDF to `.jpg`;
  * a stored name carries the hash of what is inside it, so a file is never
    overwritten and `/media` can be served as `immutable`;
  * the name also carries the id of the row that owns the picture, so two
    positions that happen to hold the same frame keep their own files — and
    deleting one of them cannot blank out the other.
"""

import hashlib
import logging
import re
import uuid
from io import BytesIO
from pathlib import Path

import pillow_heif
from fastapi import UploadFile
from PIL import Image, ImageOps, UnidentifiedImageError
from starlette.concurrency import run_in_threadpool

from faust_api.errors import (
    FileTooLargeError,
    NotFoundError,
    StorageError,
    UnsupportedFileError,
    ValidationError,
)
from faust_api.settings import get_settings

logger = logging.getLogger(__name__)

# Without this Pillow does not know what a HEIC file is, and every photo taken
# on an iPhone would be refused as an unknown format.
pillow_heif.register_heif_opener()

MAX_UPLOAD_MB = 5
MAX_UPLOAD_BYTES = MAX_UPLOAD_MB * 1024 * 1024

MENU_FOLDER = "menu"
ATMOSPHERE_FOLDER = "atmosphere"
FOLDERS = (MENU_FOLDER, ATMOSPHERE_FOLDER)

CARD_VARIANT = "card"
"""640px — what a menu card and an atmosphere tile show."""

VARIANTS: dict[str, int] = {"thumb": 320, CARD_VARIANT: 640, "full": 1280}
"""Square 1:1, cover: the showcase grid is square, so the crop happens once
here instead of in every browser (§5.3.1)."""

EXTENSION = "webp"
QUALITY = 82
"""Enough for a dark photo on a phone; below this the gradients band."""

DIGEST_LENGTH = 16

EMPTY_MESSAGE = "Файл порожній — виберіть інший"
MISSING_MESSAGE = "Виберіть фото"
BROKEN_MESSAGE = "Не вдалося прочитати зображення. Спробуйте інший файл"

MEDIA_NAME = re.compile(rf"^({'|'.join(FOLDERS)})/[0-9a-z-]{{1,90}}-({'|'.join(VARIANTS)})\.{EXTENSION}$")
"""What `/media/…` is allowed to ask for. The names are generated by the server,
so this is not a lookup — it is the thing that keeps `../../etc/passwd` from
being a valid photo key."""

CACHE_CONTROL = "public, max-age=31536000, immutable"
"""A year, and never re-checked: the name changes whenever the content does."""


def photo_url(image_key: str | None) -> str | None:
    """Absolute URL of a stored photo, or `None` when there is no photo.

    The database keeps the key, the frontend gets the address — it must not
    learn the layout of the volume (§5.2).
    """
    if not image_key:
        return None

    return f"{get_settings().media_prefix}/{image_key}-{CARD_VARIANT}.{EXTENSION}"


# ── Reading the upload ────────────────────────────────────────────────────


async def accept_upload(file: UploadFile | None) -> bytes:
    """The bytes of an upload, or a refusal the owner can act on.

    The size is checked before anything is decoded, because a 6 MB frame is a
    refusal no matter what is inside it — and the wording matches the check the
    browser already did, so it does not matter to the owner who said no.
    """
    # A missing or empty file is a form that was not filled in, not a format
    # the API refuses to read — so it comes back named, the way the field
    # errors of every other form do.
    if file is None:
        raise ValidationError(MISSING_MESSAGE, fields={"file": MISSING_MESSAGE})

    data = await file.read()

    if not data:
        raise ValidationError(EMPTY_MESSAGE, fields={"file": EMPTY_MESSAGE})

    if len(data) > MAX_UPLOAD_BYTES:
        raise FileTooLargeError.for_size(len(data), MAX_UPLOAD_MB)

    return data


# ── Recognising the format ────────────────────────────────────────────────

HEIF_BRANDS = frozenset(
    {b"heic", b"heix", b"hevc", b"hevx", b"heim", b"heis", b"hevm", b"hevs", b"mif1", b"msf1"}
)
"""ISO-BMFF brands that mean "a picture", not "a video". `avif` is deliberately
absent: the contract lists jpeg, png, webp and heic (§5.3.1)."""


def detect_format(data: bytes) -> str:
    """The real format, read out of the first bytes of the file.

    An extension is a claim by whoever uploaded the file; this is evidence.
    """
    if data.startswith(b"\xff\xd8\xff"):
        return "jpeg"

    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return "png"

    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "webp"

    if data[4:8] == b"ftyp" and data[8:12] in HEIF_BRANDS:
        return "heic"

    raise UnsupportedFileError()


# ── Storing ───────────────────────────────────────────────────────────────


def storage_root() -> Path:
    return get_settings().upload_dir


def file_path(image_key: str, variant: str) -> Path:
    return storage_root() / f"{image_key}-{variant}.{EXTENSION}"


def _prepare(data: bytes) -> Image.Image:
    """Decoded, turned the right way up and stripped of everything but pixels.

    `exif_transpose` is what makes a portrait photo from a phone come out
    portrait: the camera writes the frame sideways and marks the rotation in
    EXIF, and every viewer that ignores the tag shows it on its side.
    """
    try:
        image = Image.open(BytesIO(data))
        image.load()
        upright = ImageOps.exif_transpose(image) or image
    except (UnidentifiedImageError, OSError, ValueError, Image.DecompressionBombError) as error:
        raise UnsupportedFileError(BROKEN_MESSAGE, details=repr(error)) from error

    transparent = upright.mode in {"RGBA", "LA"} or (upright.mode == "P" and "transparency" in upright.info)

    return upright.convert("RGBA" if transparent else "RGB")


def _render(image: Image.Image, size: int) -> bytes:
    """One square variant, with no metadata attached to it.

    `info` is cleared rather than trusted: Pillow copies EXIF, ICC and XMP over
    from the source and writes them back out on save, which would leave the
    GPS coordinates of the bar inside every photo of a cocktail.
    """
    fitted = ImageOps.fit(image, (size, size), method=Image.Resampling.LANCZOS)
    fitted.info = {}

    buffer = BytesIO()
    fitted.save(buffer, format="WEBP", quality=QUALITY, method=6)

    return buffer.getvalue()


def _write(image_key: str, rendered: dict[str, bytes]) -> None:
    """All three variants onto the volume, or none of them.

    Each file is written beside its final name and moved into place, so a
    reader never sees a half-written photo. A failure halfway through takes the
    files already written with it — the database still points at the old key,
    and a stray pair of files would be dead weight nobody would ever clean up.
    """
    written: list[Path] = []

    try:
        for variant, payload in rendered.items():
            target = file_path(image_key, variant)
            target.parent.mkdir(parents=True, exist_ok=True)

            staged = target.with_suffix(f".{EXTENSION}.part")
            staged.write_bytes(payload)
            staged.replace(target)

            written.append(target)
    except OSError as error:
        for path in written:
            path.unlink(missing_ok=True)

        logger.exception("[images] не вдалося записати %s", image_key)
        raise StorageError(details=repr(error)) from error


def _store(folder: str, owner: uuid.UUID, data: bytes) -> str:
    detect_format(data)

    image = _prepare(data)
    digest = hashlib.sha256(data).hexdigest()[:DIGEST_LENGTH]
    image_key = f"{folder}/{owner.hex}-{digest}"

    _write(image_key, {variant: _render(image, size) for variant, size in VARIANTS.items()})

    return image_key


async def store_photo(folder: str, owner: uuid.UUID, data: bytes) -> str:
    """Saves a picture and answers with its storage key.

    Pillow is blocking and a 5 MB frame is not instant, so the work goes to a
    thread — otherwise one upload would stall every other request the API is
    serving.
    """
    return await run_in_threadpool(_store, folder, owner, data)


def _remove(image_key: str) -> None:
    for variant in VARIANTS:
        file_path(image_key, variant).unlink(missing_ok=True)


async def remove_photo(image_key: str | None) -> None:
    """Deletes every variant of a photo. Never raises.

    It runs after the row is already gone or already points elsewhere, so a
    volume that refuses to delete must not turn a finished job into an error
    for the owner. What it leaves behind is a stray file and a line in the log.
    """
    if not image_key:
        return

    try:
        await run_in_threadpool(_remove, image_key)
    except OSError as error:
        logger.warning("[images] не вдалося прибрати файли %s: %s", image_key, error)


# ── Serving ───────────────────────────────────────────────────────────────


def resolve_media(name: str) -> Path:
    """The file behind `/media/<name>`, or a 404.

    The name is checked against the shape the server itself generates before it
    ever becomes a path: a request is not allowed to describe a location, only
    to name a photo.
    """
    if not MEDIA_NAME.match(name):
        raise NotFoundError("Такого фото немає")

    path = storage_root() / name

    if not path.is_file():
        raise NotFoundError("Такого фото немає")

    return path
